/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.Telaexcluirnaousada.TelaExcluirReceita;
import controle.ConexaoBD;
import controle.ControleReceita;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloReceita;
import modelo.ModeloTabela;


public class TelaReceita extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    ModeloReceita rec = new ModeloReceita();
    ControleReceita control = new ControleReceita();
    
    public TelaReceita() {
        initComponents();
        preencherTabela("select *from adicionarreceita order by cod_adicionarreceita");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExReceita = new javax.swing.JButton();
        jButtonReceitaVoltar = new javax.swing.JButton();
        jScrollPaneReceita = new javax.swing.JScrollPane();
        jTableReceita = new javax.swing.JTable();
        jButtonAdcReceita = new javax.swing.JButton();
        jButtonEdReceita = new javax.swing.JButton();
        jLabelReceita = new javax.swing.JLabel();
        jLabelTelaReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonExReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jButtonExReceita.setText("Exluir Gasto");
        jButtonExReceita.setEnabled(false);
        jButtonExReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExReceita);
        jButtonExReceita.setBounds(120, 210, 40, 40);

        jButtonReceitaVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        jButtonReceitaVoltar.setText("Voltar");
        jButtonReceitaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitaVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReceitaVoltar);
        jButtonReceitaVoltar.setBounds(30, 103, 40, 40);

        jTableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceitaMouseClicked(evt);
            }
        });
        jScrollPaneReceita.setViewportView(jTableReceita);

        getContentPane().add(jScrollPaneReceita);
        jScrollPaneReceita.setBounds(20, 280, 230, 200);

        jButtonAdcReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar.png"))); // NOI18N
        jButtonAdcReceita.setText("Adicionar Gasto");
        jButtonAdcReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdcReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdcReceita);
        jButtonAdcReceita.setBounds(40, 210, 40, 40);

        jButtonEdReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jButtonEdReceita.setText("Editar Gasto");
        jButtonEdReceita.setEnabled(false);
        jButtonEdReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdReceita);
        jButtonEdReceita.setBounds(200, 210, 40, 30);

        jLabelReceita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReceita.setText("Receita");
        getContentPane().add(jLabelReceita);
        jLabelReceita.setBounds(120, 160, 60, 22);

        jLabelTelaReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaReceita);
        jLabelTelaReceita.setBounds(0, 0, 267, 544);

        setSize(new java.awt.Dimension(284, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExReceitaActionPerformed
        int  resposta = 0;
        conex.conexao();
        int gastoLinha= jTableReceita.getSelectedRow();
        int gastoColuna = 0;
        int pegatabela = Integer.parseInt(jTableReceita.getValueAt(gastoLinha, gastoColuna).toString());
        resposta = JOptionPane.showConfirmDialog(rootPane, "Excluir receita?");
        if (resposta == JOptionPane.YES_OPTION){
            rec.setCodigo(pegatabela);
            control.Excluir(rec);
            TelaReceita tela = new TelaReceita();
            tela.setVisible(true);
            dispose();
        }
        conex.desconecta();
    }//GEN-LAST:event_jButtonExReceitaActionPerformed

    private void jButtonAdcReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdcReceitaActionPerformed
        TelaInsercaoReceita tela = new TelaInsercaoReceita();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAdcReceitaActionPerformed

    private void jButtonReceitaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitaVoltarActionPerformed
        MenuPrincipal tela = new MenuPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReceitaVoltarActionPerformed

    private void jButtonEdReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdReceitaActionPerformed
        TelaEditarReceita tela = new TelaEditarReceita();
        tela.setVisible(true);
        dispose();
        int gastoLinha = jTableReceita.getSelectedRow();
        int gastoColuna = 0;
        int pegatabela = Integer.parseInt(jTableReceita.getValueAt(gastoLinha, gastoColuna).toString());
        TelaEditarReceita.cod = pegatabela;
    }//GEN-LAST:event_jButtonEdReceitaActionPerformed

    private void jTableReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceitaMouseClicked
        jButtonExReceita.setEnabled(true);
        jButtonEdReceita.setEnabled(true);
    }//GEN-LAST:event_jTableReceitaMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Cod","Valor","Data"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_adicionarreceita"),conex.rs.getFloat("valor_adicionarreceita"),conex.rs.getDate("data_adicionarreceita")});
            }while(conex.rs.next());
        }catch(SQLException ex){

        }
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        
        jTableReceita.setModel(modelo);
        jTableReceita.getColumnModel().getColumn(0).setPreferredWidth(44);
        jTableReceita.getColumnModel().getColumn(0).setResizable(false);
        jTableReceita.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableReceita.getColumnModel().getColumn(1).setResizable(false);
        jTableReceita.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableReceita.getColumnModel().getColumn(2).setResizable(false);
        jTableReceita.getTableHeader().setReorderingAllowed(false);
        jTableReceita.setAutoResizeMode(jTableReceita.AUTO_RESIZE_OFF);
        jTableReceita.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdcReceita;
    private javax.swing.JButton jButtonEdReceita;
    private javax.swing.JButton jButtonExReceita;
    private javax.swing.JButton jButtonReceitaVoltar;
    private javax.swing.JLabel jLabelReceita;
    private javax.swing.JLabel jLabelTelaReceita;
    private javax.swing.JScrollPane jScrollPaneReceita;
    private javax.swing.JTable jTableReceita;
    // End of variables declaration//GEN-END:variables
}
