/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import controle.ConexaoBD;
import controle.ControleGastos;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.ModeloGastos;

public class TelaInsercaoGasto extends javax.swing.JFrame {

    ModeloGastos gast = new ModeloGastos();
    ControleGastos control = new ControleGastos();
    ConexaoBD conex = new ConexaoBD();
    
    public TelaInsercaoGasto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelInsGasto = new javax.swing.JButton();
        jButtonOkInsGasto = new javax.swing.JButton();
        jLabelValorInsGasto = new javax.swing.JLabel();
        jTextFieldInsGasto = new javax.swing.JTextField();
        jLabelTelaInsGasto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelInsGasto.setText("Cancel");
        jButtonCancelInsGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelInsGastoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelInsGasto);
        jButtonCancelInsGasto.setBounds(170, 320, 80, 23);

        jButtonOkInsGasto.setText("Ok");
        jButtonOkInsGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkInsGastoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkInsGasto);
        jButtonOkInsGasto.setBounds(40, 320, 73, 23);

        jLabelValorInsGasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValorInsGasto.setText("Valor: ");
        getContentPane().add(jLabelValorInsGasto);
        jLabelValorInsGasto.setBounds(130, 200, 39, 30);

        jTextFieldInsGasto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInsGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsGastoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldInsGasto);
        jTextFieldInsGasto.setBounds(70, 230, 160, 70);

        jLabelTelaInsGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaInsGasto);
        jLabelTelaInsGasto.setBounds(10, 0, 267, 544);

        setSize(new java.awt.Dimension(304, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelInsGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelInsGastoActionPerformed
        TelaGastos tela = new TelaGastos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelInsGastoActionPerformed

    private void jTextFieldInsGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsGastoActionPerformed

    }//GEN-LAST:event_jTextFieldInsGastoActionPerformed

    private void jButtonOkInsGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkInsGastoActionPerformed
        
        try {
             
             Float.valueOf(jTextFieldInsGasto.getText());
             gast.setValor(Float.parseFloat(jTextFieldInsGasto.getText()));
             gast.setData(Date.valueOf(LocalDate.now()));
             control.Salvar(gast);
             TelaGastos tela = new TelaGastos();
             tela.setVisible(true);
             dispose();
       }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Número Invalido");
            jTextFieldInsGasto.setText("");
            
        }   
    }//GEN-LAST:event_jButtonOkInsGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInsercaoGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelInsGasto;
    private javax.swing.JButton jButtonOkInsGasto;
    private javax.swing.JLabel jLabelTelaInsGasto;
    private javax.swing.JLabel jLabelValorInsGasto;
    private javax.swing.JTextField jTextFieldInsGasto;
    // End of variables declaration//GEN-END:variables

}
