/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleDestino;
import java.sql.Date;
import java.time.LocalDate;
import modelo.ModeloDestino;

public class TelaEditarDestino extends javax.swing.JFrame {

    static int codd;
    ModeloDestino dest = new ModeloDestino();
    ControleDestino control = new ControleDestino();
    
    public TelaEditarDestino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelEditDestino = new javax.swing.JButton();
        jButtonOkEditDestino = new javax.swing.JButton();
        jLabelValorEditDestino = new javax.swing.JLabel();
        jTextFieldEditDestino = new javax.swing.JTextField();
        jLabelTelaEditDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelEditDestino.setText("Cancel");
        jButtonCancelEditDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelEditDestino);
        jButtonCancelEditDestino.setBounds(170, 320, 80, 23);

        jButtonOkEditDestino.setText("Ok");
        jButtonOkEditDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEditDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkEditDestino);
        jButtonOkEditDestino.setBounds(40, 320, 73, 23);

        jLabelValorEditDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValorEditDestino.setText("Novo Nome: ");
        getContentPane().add(jLabelValorEditDestino);
        jLabelValorEditDestino.setBounds(110, 200, 90, 30);

        jTextFieldEditDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEditDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEditDestino);
        jTextFieldEditDestino.setBounds(70, 230, 160, 70);

        jLabelTelaEditDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaEditDestino);
        jLabelTelaEditDestino.setBounds(10, 0, 290, 544);

        setSize(new java.awt.Dimension(297, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelEditDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditDestinoActionPerformed
        TelaDestino tela = new TelaDestino();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelEditDestinoActionPerformed

    private void jTextFieldEditDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditDestinoActionPerformed

    private void jButtonOkEditDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEditDestinoActionPerformed
        String aux = String.valueOf(jTextFieldEditDestino.getText());
        dest.setCodigo(codd);
        dest.setNome(aux);
        dest.setData(Date.valueOf(LocalDate.now()));
        control.Editar(dest);
        TelaDestino tela = new TelaDestino();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonOkEditDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditDestino;
    private javax.swing.JButton jButtonOkEditDestino;
    private javax.swing.JLabel jLabelTelaEditDestino;
    private javax.swing.JLabel jLabelValorEditDestino;
    private javax.swing.JTextField jTextFieldEditDestino;
    // End of variables declaration//GEN-END:variables
}
