/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import controle.ControleReceita;
import javax.swing.JOptionPane;
import modelo.ModeloReceita;
import java.sql.Date;
import java.time.LocalDate;

public class TelaEditarReceita extends javax.swing.JFrame {

    static int cod;
    ConexaoBD conex = new ConexaoBD();
    ModeloReceita gast = new ModeloReceita();
    ControleReceita control = new ControleReceita();
    
    public TelaEditarReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelEditReceita = new javax.swing.JButton();
        jButtonOkEditReceita = new javax.swing.JButton();
        jLabelValorEditReceita = new javax.swing.JLabel();
        jTextFieldEditReceita = new javax.swing.JTextField();
        jLabelTelaEditReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelEditReceita.setText("Cancel");
        jButtonCancelEditReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelEditReceita);
        jButtonCancelEditReceita.setBounds(170, 320, 80, 23);

        jButtonOkEditReceita.setText("Ok");
        jButtonOkEditReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEditReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkEditReceita);
        jButtonOkEditReceita.setBounds(40, 320, 73, 23);

        jLabelValorEditReceita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValorEditReceita.setText("Novo Valor: ");
        getContentPane().add(jLabelValorEditReceita);
        jLabelValorEditReceita.setBounds(110, 200, 76, 30);

        jTextFieldEditReceita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldEditReceita);
        jTextFieldEditReceita.setBounds(70, 230, 160, 70);

        jLabelTelaEditReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaEditReceita);
        jLabelTelaEditReceita.setBounds(10, 0, 270, 544);

        setSize(new java.awt.Dimension(297, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelEditReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditReceitaActionPerformed
        TelaReceita tela = new TelaReceita();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelEditReceitaActionPerformed

    private void jButtonOkEditReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEditReceitaActionPerformed
         try {
             
             float aux = Float.valueOf(jTextFieldEditReceita.getText());
             Float.valueOf(jTextFieldEditReceita.getText());
             gast.setCodigo(cod);
             gast.setValor(aux);
             gast.setData(Date.valueOf(LocalDate.now()));
             control.Editar(gast);
             TelaReceita tela = new TelaReceita();
             tela.setVisible(true);
             dispose();
             

       }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Número Invalido");
            jTextFieldEditReceita.setText("");
        }  
    }//GEN-LAST:event_jButtonOkEditReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditReceita;
    private javax.swing.JButton jButtonOkEditReceita;
    private javax.swing.JLabel jLabelTelaEditReceita;
    private javax.swing.JLabel jLabelValorEditReceita;
    private javax.swing.JTextField jTextFieldEditReceita;
    // End of variables declaration//GEN-END:variables
}
