/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import controle.ControleGastos;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloGastos;
import modelo.ModeloTabela;

public class TelaEditarGastos extends javax.swing.JFrame {
    static int codigo;

    ConexaoBD conex = new ConexaoBD();
    ModeloGastos gast = new ModeloGastos();
    ControleGastos control = new ControleGastos();
    
    public TelaEditarGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelEditGastos = new javax.swing.JButton();
        jButtonOkEditGastos = new javax.swing.JButton();
        jLabelValorEditGastos = new javax.swing.JLabel();
        jTextFieldEditGastos = new javax.swing.JTextField();
        jLabelTelaEditGastos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelEditGastos.setText("Cancel");
        jButtonCancelEditGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelEditGastos);
        jButtonCancelEditGastos.setBounds(170, 320, 80, 23);

        jButtonOkEditGastos.setText("Ok");
        jButtonOkEditGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEditGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkEditGastos);
        jButtonOkEditGastos.setBounds(40, 320, 73, 23);

        jLabelValorEditGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValorEditGastos.setText("Novo Valor: ");
        getContentPane().add(jLabelValorEditGastos);
        jLabelValorEditGastos.setBounds(110, 200, 76, 30);

        jTextFieldEditGastos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEditGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEditGastos);
        jTextFieldEditGastos.setBounds(70, 230, 160, 70);

        jLabelTelaEditGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaEditGastos);
        jLabelTelaEditGastos.setBounds(10, 0, 280, 544);

        setSize(new java.awt.Dimension(293, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelEditGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditGastosActionPerformed
        TelaGastos tela = new TelaGastos();
        tela.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonCancelEditGastosActionPerformed

    private void jButtonOkEditGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEditGastosActionPerformed
        try {
             
             float aux = Float.valueOf(jTextFieldEditGastos.getText());
             gast.setCodigo(codigo);
             gast.setValor(aux);
             gast.setData(Date.valueOf(LocalDate.now()));
             control.Editar(gast);
             TelaGastos tela = new TelaGastos();
             tela.setVisible(true);
             dispose();
       }
        catch (NumberFormatException e) {
            jTextFieldEditGastos.setText("");
            
        } 

    }//GEN-LAST:event_jButtonOkEditGastosActionPerformed


    private void jTextFieldEditGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditGastos;
    private javax.swing.JButton jButtonOkEditGastos;
    private javax.swing.JLabel jLabelTelaEditGastos;
    private javax.swing.JLabel jLabelValorEditGastos;
    private javax.swing.JTextField jTextFieldEditGastos;
    // End of variables declaration//GEN-END:variables
}
