/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import controle.ControleReceita;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.ModeloReceita;

public class TelaInsercaoReceita extends javax.swing.JFrame {
   
    ModeloReceita rec = new ModeloReceita();
    ControleReceita control = new ControleReceita();
    ConexaoBD conex = new ConexaoBD();

    
    public TelaInsercaoReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelInsReceita = new javax.swing.JButton();
        jButton1OkInsReceita = new javax.swing.JButton();
        jLabel1ValorInsReceita = new javax.swing.JLabel();
        jTextFieldInsReceita = new javax.swing.JTextField();
        jLabelTelaInsReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelInsReceita.setText("Cancel");
        jButtonCancelInsReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelInsReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelInsReceita);
        jButtonCancelInsReceita.setBounds(170, 320, 80, 23);

        jButton1OkInsReceita.setText("Ok");
        jButton1OkInsReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OkInsReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1OkInsReceita);
        jButton1OkInsReceita.setBounds(40, 320, 73, 23);

        jLabel1ValorInsReceita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1ValorInsReceita.setText("Valor: ");
        getContentPane().add(jLabel1ValorInsReceita);
        jLabel1ValorInsReceita.setBounds(130, 200, 39, 30);

        jTextFieldInsReceita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldInsReceita);
        jTextFieldInsReceita.setBounds(70, 230, 160, 70);

        jLabelTelaInsReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaInsReceita);
        jLabelTelaInsReceita.setBounds(10, 0, 267, 544);

        setSize(new java.awt.Dimension(297, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelInsReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelInsReceitaActionPerformed
        TelaReceita tela = new TelaReceita();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelInsReceitaActionPerformed

    private void jButton1OkInsReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OkInsReceitaActionPerformed
        try {
             
             Float.valueOf(jTextFieldInsReceita.getText());
             rec.setValor(Float.parseFloat(jTextFieldInsReceita.getText()));
             rec.setData(Date.valueOf(LocalDate.now()));
             control.Salvar(rec);
             TelaReceita tela = new TelaReceita();
             tela.setVisible(true);
             dispose();
             
       }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Número Invalido");
            jTextFieldInsReceita.setText("");
            
        } 
    }//GEN-LAST:event_jButton1OkInsReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInsercaoReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1OkInsReceita;
    private javax.swing.JButton jButtonCancelInsReceita;
    private javax.swing.JLabel jLabel1ValorInsReceita;
    private javax.swing.JLabel jLabelTelaInsReceita;
    private javax.swing.JTextField jTextFieldInsReceita;
    // End of variables declaration//GEN-END:variables
}
