/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.Telaexcluirnaousada.TelaExcluirDestino;
import controle.ConexaoBD;
import controle.ControleDestino;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloDestino;
import modelo.ModeloTabela;

public class TelaDestino extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    ModeloDestino dest = new ModeloDestino();
    ControleDestino control = new ControleDestino();
    
    public TelaDestino() {
        initComponents();
        preencherTabela("select *from adicionardestino order by cod_adicionardestino");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExDestino = new javax.swing.JButton();
        jButtonDestinoVoltar = new javax.swing.JButton();
        jScrollPaneDestino = new javax.swing.JScrollPane();
        jTableDestino = new javax.swing.JTable();
        jButtonAdcDestino = new javax.swing.JButton();
        jButtonEdDestino = new javax.swing.JButton();
        jLabeDestino = new javax.swing.JLabel();
        jLabelTelaDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonExDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jButtonExDestino.setText("Exluir Gasto");
        jButtonExDestino.setEnabled(false);
        jButtonExDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExDestino);
        jButtonExDestino.setBounds(110, 210, 40, 40);

        jButtonDestinoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        jButtonDestinoVoltar.setText("Voltar");
        jButtonDestinoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestinoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDestinoVoltar);
        jButtonDestinoVoltar.setBounds(20, 100, 40, 40);

        jTableDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDestinoMouseClicked(evt);
            }
        });
        jScrollPaneDestino.setViewportView(jTableDestino);

        getContentPane().add(jScrollPaneDestino);
        jScrollPaneDestino.setBounds(20, 290, 230, 190);

        jButtonAdcDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar.png"))); // NOI18N
        jButtonAdcDestino.setText("Adicionar Gasto");
        jButtonAdcDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdcDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdcDestino);
        jButtonAdcDestino.setBounds(30, 210, 40, 40);

        jButtonEdDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jButtonEdDestino.setText("Editar Gasto");
        jButtonEdDestino.setEnabled(false);
        jButtonEdDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdDestino);
        jButtonEdDestino.setBounds(190, 210, 40, 30);

        jLabeDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeDestino.setText("Destino");
        getContentPane().add(jLabeDestino);
        jLabeDestino.setBounds(110, 160, 60, 22);

        jLabelTelaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaDestino);
        jLabelTelaDestino.setBounds(0, 0, 267, 544);

        setSize(new java.awt.Dimension(283, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExDestinoActionPerformed
        int  resposta = 0;
        conex.conexao();
        int gastoLinha= jTableDestino.getSelectedRow();
        int gastoColuna = 0;
        int pegatabela = Integer.parseInt(jTableDestino.getValueAt(gastoLinha, gastoColuna).toString());
        resposta = JOptionPane.showConfirmDialog(rootPane, "Excluir destino?");
        if (resposta == JOptionPane.YES_OPTION){
            dest.setCodigo(pegatabela);
            control.Excluir(dest);
            TelaDestino tela = new TelaDestino();
            tela.setVisible(true);
            dispose();
        }
        conex.desconecta();
    }//GEN-LAST:event_jButtonExDestinoActionPerformed

    private void jButtonAdcDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdcDestinoActionPerformed
        TelaInsercaoDestino tela = new TelaInsercaoDestino();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAdcDestinoActionPerformed

    private void jButtonDestinoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestinoVoltarActionPerformed
        MenuPrincipal tela = new MenuPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDestinoVoltarActionPerformed

    private void jButtonEdDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdDestinoActionPerformed
        TelaEditarDestino tela = new TelaEditarDestino();
        tela.setVisible(true);
        dispose();
        int destinoLinha = 0;
        int destinoColuna = 0;
        int pegatabela = Integer.parseInt(jTableDestino.getValueAt(destinoLinha, destinoColuna).toString());
        TelaEditarDestino.codd = pegatabela;
        
    }//GEN-LAST:event_jButtonEdDestinoActionPerformed

    private void jTableDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDestinoMouseClicked
        jButtonExDestino.setEnabled(true);
        jButtonEdDestino.setEnabled(true);
    }//GEN-LAST:event_jTableDestinoMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Cod","Nome","Data"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_adicionardestino"),conex.rs.getString("nome_adicionardestino"),conex.rs.getDate("data_adicionardestino")});
            }while(conex.rs.next());
        }catch(SQLException ex){

        }
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        
        jTableDestino.setModel(modelo);
        jTableDestino.getColumnModel().getColumn(0).setPreferredWidth(44);
        jTableDestino.getColumnModel().getColumn(0).setResizable(false);
        jTableDestino.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableDestino.getColumnModel().getColumn(1).setResizable(false);
        jTableDestino.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableDestino.getColumnModel().getColumn(2).setResizable(false);
        jTableDestino.getTableHeader().setReorderingAllowed(false);
        jTableDestino.setAutoResizeMode(jTableDestino.AUTO_RESIZE_OFF);
        jTableDestino.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdcDestino;
    private javax.swing.JButton jButtonDestinoVoltar;
    private javax.swing.JButton jButtonEdDestino;
    private javax.swing.JButton jButtonExDestino;
    private javax.swing.JLabel jLabeDestino;
    private javax.swing.JLabel jLabelTelaDestino;
    private javax.swing.JScrollPane jScrollPaneDestino;
    private javax.swing.JTable jTableDestino;
    // End of variables declaration//GEN-END:variables
}
