/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import controle.ControleDestino;
import java.sql.Date;
import java.time.LocalDate;
import modelo.ModeloDestino;

public class TelaInsercaoDestino extends javax.swing.JFrame {

    ModeloDestino dest = new ModeloDestino();
    ControleDestino control = new ControleDestino();
    ConexaoBD conex = new ConexaoBD();
    
    
    public TelaInsercaoDestino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelInsDestino = new javax.swing.JButton();
        jButtonOkInsDestino = new javax.swing.JButton();
        jLabelValorInsDestino = new javax.swing.JLabel();
        jTextFieldInsDestino = new javax.swing.JTextField();
        jLabelTelaInsDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelInsDestino.setText("Cancel");
        jButtonCancelInsDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelInsDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelInsDestino);
        jButtonCancelInsDestino.setBounds(170, 320, 80, 23);

        jButtonOkInsDestino.setText("Ok");
        jButtonOkInsDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkInsDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOkInsDestino);
        jButtonOkInsDestino.setBounds(40, 320, 73, 23);

        jLabelValorInsDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValorInsDestino.setText("Nome:");
        getContentPane().add(jLabelValorInsDestino);
        jLabelValorInsDestino.setBounds(130, 200, 50, 30);

        jTextFieldInsDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldInsDestino);
        jTextFieldInsDestino.setBounds(70, 230, 160, 70);

        jLabelTelaInsDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaInsDestino);
        jLabelTelaInsDestino.setBounds(10, 0, 267, 544);

        setSize(new java.awt.Dimension(297, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelInsDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelInsDestinoActionPerformed
        TelaDestino tela = new TelaDestino();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelInsDestinoActionPerformed

    private void jButtonOkInsDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkInsDestinoActionPerformed
         LocalDate data = java.time.LocalDate.now(); 
         dest.setNome(jTextFieldInsDestino.getText());
         dest.setData(Date.valueOf(LocalDate.now()));
         control.Salvar(dest);
         TelaDestino tela = new TelaDestino();
         tela.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButtonOkInsDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInsercaoDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInsercaoDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelInsDestino;
    private javax.swing.JButton jButtonOkInsDestino;
    private javax.swing.JLabel jLabelTelaInsDestino;
    private javax.swing.JLabel jLabelValorInsDestino;
    private javax.swing.JTextField jTextFieldInsDestino;
    // End of variables declaration//GEN-END:variables
}
