/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBD;
import controle.ControleGastos;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloGastos;
import modelo.ModeloTabela;

public class TelaGastos extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    ModeloGastos gast = new ModeloGastos();
    ControleGastos control = new ControleGastos();

    
    public TelaGastos() {
        initComponents();
        preencherTabela("select *from adicionargastos order by cod_adicionargastos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGastos = new javax.swing.JTable();
        jButtonExGastos = new javax.swing.JButton();
        jButtonGastoVoltar = new javax.swing.JButton();
        jButtonAdcGastos = new javax.swing.JButton();
        jButtonEdGastos = new javax.swing.JButton();
        jLabelGastos = new javax.swing.JLabel();
        jLabelTelaGastos = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGastosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGastos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 270, 230, 210);

        jButtonExGastos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExGastos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jButtonExGastos.setText("Exluir Gasto");
        jButtonExGastos.setEnabled(false);
        jButtonExGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExGastos);
        jButtonExGastos.setBounds(120, 210, 40, 40);

        jButtonGastoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        jButtonGastoVoltar.setText("Voltar");
        jButtonGastoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGastoVoltar);
        jButtonGastoVoltar.setBounds(30, 103, 40, 40);

        jButtonAdcGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicionar.png"))); // NOI18N
        jButtonAdcGastos.setText("Adicionar Gasto");
        jButtonAdcGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdcGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdcGastos);
        jButtonAdcGastos.setBounds(40, 210, 40, 40);

        jButtonEdGastos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEdGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        jButtonEdGastos.setText("Editar Gasto");
        jButtonEdGastos.setEnabled(false);
        jButtonEdGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdGastos);
        jButtonEdGastos.setBounds(200, 210, 40, 30);

        jLabelGastos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGastos.setText("Gastos");
        getContentPane().add(jLabelGastos);
        jLabelGastos.setBounds(120, 160, 60, 22);

        jLabelTelaGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelaGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaGastos);
        jLabelTelaGastos.setBounds(10, 0, 267, 544);

        setSize(new java.awt.Dimension(300, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdcGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdcGastosActionPerformed
        TelaInsercaoGasto tela = new TelaInsercaoGasto();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAdcGastosActionPerformed

    private void jButtonExGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExGastosActionPerformed
        int  resposta = 0;
        conex.conexao();
        int gastoLinha = jTableGastos.getSelectedRow();
        int gastoColuna = 0;
        int pegatabela = Integer.parseInt(jTableGastos.getValueAt(gastoLinha, gastoColuna).toString());
        resposta = JOptionPane.showConfirmDialog(rootPane, "Excluir gasto?");
        if (resposta == JOptionPane.YES_OPTION){
            gast.setCodigo(pegatabela);
            control.Excluir(gast);
            TelaGastos tela = new TelaGastos();
            tela.setVisible(true);
            dispose();
        }
        conex.desconecta();
    }//GEN-LAST:event_jButtonExGastosActionPerformed

    private void jButtonGastoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastoVoltarActionPerformed
        MenuPrincipal tela = new MenuPrincipal();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonGastoVoltarActionPerformed

    private void jButtonEdGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdGastosActionPerformed
        TelaEditarGastos tela = new TelaEditarGastos();
        tela.setVisible(true);
        dispose();
        int gastoLinha = jTableGastos.getSelectedRow();
        int gastoColuna = 0;
        int pegatabela = Integer.parseInt(jTableGastos.getValueAt(gastoLinha, gastoColuna).toString());
        TelaEditarGastos.codigo = pegatabela;
    }//GEN-LAST:event_jButtonEdGastosActionPerformed


    private void jTableGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGastosMouseClicked
        jButtonExGastos.setEnabled(true);
        jButtonEdGastos.setEnabled(true);
    }//GEN-LAST:event_jTableGastosMouseClicked


    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Cod","Valor","Data"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_adicionargastos"),conex.rs.getFloat("valor_adicionargastos"),conex.rs.getDate("data_adicionargastos")});
            }while(conex.rs.next());
        }catch(SQLException ex){

        }
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        
        jTableGastos.setModel(modelo);
        jTableGastos.getColumnModel().getColumn(0).setPreferredWidth(44);
        jTableGastos.getColumnModel().getColumn(0).setResizable(false);
        jTableGastos.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableGastos.getColumnModel().getColumn(1).setResizable(false);
        jTableGastos.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableGastos.getColumnModel().getColumn(2).setResizable(false);
        jTableGastos.getTableHeader().setReorderingAllowed(false);
        jTableGastos.setAutoResizeMode(jTableGastos.AUTO_RESIZE_OFF);
        jTableGastos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdcGastos;
    private javax.swing.JButton jButtonEdGastos;
    private javax.swing.JButton jButtonExGastos;
    private javax.swing.JButton jButtonGastoVoltar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelTelaGastos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGastos;
    // End of variables declaration//GEN-END:variables
}
