/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Telaexcluirnaousada;

import visao.TelaGastos;

/**
 *
 * @author Renato
 */
public class TelaExcluirGastos extends javax.swing.JFrame {

    /**
     * Creates new form TelaExcluirGastos
     */
    public TelaExcluirGastos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelExcluirGastos = new javax.swing.JButton();
        jButtonOkExcluirGastos = new javax.swing.JButton();
        jLabelMsgExcluirGastos = new javax.swing.JLabel();
        jLabelTelaInsDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelExcluirGastos.setText("Cancel");
        jButtonCancelExcluirGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelExcluirGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelExcluirGastos);
        jButtonCancelExcluirGastos.setBounds(170, 280, 80, 23);

        jButtonOkExcluirGastos.setText("Ok");
        getContentPane().add(jButtonOkExcluirGastos);
        jButtonOkExcluirGastos.setBounds(50, 280, 73, 23);

        jLabelMsgExcluirGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMsgExcluirGastos.setText("Você deseja excluir este gasto?");
        getContentPane().add(jLabelMsgExcluirGastos);
        jLabelMsgExcluirGastos.setBounds(60, 210, 190, 30);

        jLabelTelaInsDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaInsDestino);
        jLabelTelaInsDestino.setBounds(10, 0, 290, 544);

        setSize(new java.awt.Dimension(294, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelExcluirGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelExcluirGastosActionPerformed
        TelaGastos tela = new TelaGastos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelExcluirGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluirGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelExcluirGastos;
    private javax.swing.JButton jButtonOkExcluirGastos;
    private javax.swing.JLabel jLabelMsgExcluirGastos;
    private javax.swing.JLabel jLabelTelaInsDestino;
    // End of variables declaration//GEN-END:variables
}
