/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Telaexcluirnaousada;

import visao.TelaReceita;

/**
 *
 * @author Renato
 */
public class TelaExcluirReceita extends javax.swing.JFrame {

    /**
     * Creates new form TelaExcluirReceita
     */
    public TelaExcluirReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelExcluirReceita = new javax.swing.JButton();
        jButtonOkExcluirReceita = new javax.swing.JButton();
        jLabelMsgExcluirDestino = new javax.swing.JLabel();
        jLabelTelaExcluirReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelExcluirReceita.setText("Cancel");
        jButtonCancelExcluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelExcluirReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelExcluirReceita);
        jButtonCancelExcluirReceita.setBounds(170, 280, 80, 23);

        jButtonOkExcluirReceita.setText("Ok");
        getContentPane().add(jButtonOkExcluirReceita);
        jButtonOkExcluirReceita.setBounds(50, 280, 73, 23);

        jLabelMsgExcluirDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMsgExcluirDestino.setText("Você deseja excluir esta Receita?");
        getContentPane().add(jLabelMsgExcluirDestino);
        jLabelMsgExcluirDestino.setBounds(50, 210, 210, 30);

        jLabelTelaExcluirReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu principal.png"))); // NOI18N
        getContentPane().add(jLabelTelaExcluirReceita);
        jLabelTelaExcluirReceita.setBounds(10, 0, 270, 544);

        setSize(new java.awt.Dimension(297, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelExcluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelExcluirReceitaActionPerformed
        TelaReceita tela = new TelaReceita();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelExcluirReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluirReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelExcluirReceita;
    private javax.swing.JButton jButtonOkExcluirReceita;
    private javax.swing.JLabel jLabelMsgExcluirDestino;
    private javax.swing.JLabel jLabelTelaExcluirReceita;
    // End of variables declaration//GEN-END:variables
}
